ca_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDTDCCAjSgAwIBAgIRALVvT0n3q2Ji3hC6GSnZqOIwDQYJKoZIhvcNAQELBQAw
  GjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMB4XDTI0MTExMzEzNDQwNVoXDTM0
  MTExMTEzNDQwNVowGjEYMBYGA1UEChMPVmVsb2NpcmFwdG9yIENBMIIBIjANBgkq
  hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoCX5I+M/ZaCSahYqYHOMJixSl4ItxBiE
  cSMnrDZQI2Sf+rQ3wkBqqO2e+eahX1pNhqqbKrWW+t1gQhsubbkt5UepMXXKwnfP
  g1xw8fyXPaDXWI4hGfxc4N6WrtsaGrg/iYhhNtSVXEsQW7GTXyyM6QfKWdQfPr65
  ZhL6gSA2HHQOsmS2ftZ+hld1crrDzx1hbH3UHhZqJmEEV7VRENx851YgOfLAFxWf
  ZZcevkA4SUkMp8zU4++eSlaRFjRIKqHOe4oW9MhV2cW9Ew/4y38bYyFX6pa8g/va
  8Qh9ERdAhXjwt1mT57scHdpeEVwxiQCB09dc6YKXBq77SmL4lgQlqQIDAQABo4GM
  MIGJMA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
  AwIwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUzu97p0haQ20B7DWGCpqAiUGx
  n68wKAYDVR0RBCEwH4IdVmVsb2NpcmFwdG9yX2NhLnZlbG9jaWRleC5jb20wDQYJ
  KoZIhvcNAQELBQADggEBAGomYLApcVU/TFDp4AGGeSjj37Mbd+uDmCKf9KcNcp1Z
  U4lGnTyD97+EaIVTVsBJQCNur95RNOdkq7L4Fn+pFtDcaaEZvCwX7pTATedAg7k3
  /PsphIiQusbHCoavsulDrLKfX7KRmpf9/hctDwvvAq3Flwia+sgYn8YW20r4W2PB
  rW2lHruGHdKu5DjIsogP21GkaDMyinQGf/zQyao//05sWQAndIinKGS3mnPqacBr
  +AUAyozbfiY/qP6zazgM1A12ZD0cFaQ+bAeNnaKNQRRUqEsKHYskZIUIZKjSko4v
  Uevvnt+84OkMseZvCYZtDY+FZChbm5cuuHxl0fMuEO8=
  -----END CERTIFICATE-----
client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIDOTCCAiGgAwIBAgIQTPr4OIZGlWpNI+gC+aKHYzANBgkqhkiG9w0BAQsFADAa
  MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQxMTE0MDkyNjQ3WhcNMjUx
  MTE0MDkyNjQ3WjAlMRUwEwYDVQQKEwxWZWxvY2lyYXB0b3IxDDAKBgNVBAMTA2Fw
  aTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAPExJlxIeh+IlwEVPqGI
  47/7h6HX+BsTDQAdSyR6eTdB8v+SwFQ/z6ZwZAuHh6qa93Bs3OmKjFIwQBl0L8Dn
  1RyjRqru0OUkEn1Z9swaZqRjSsmwJ1Xp7kyNj8aWxFv/OEf9PNBabOT8ySWfmFTV
  3vbu4vKVyf66ntQj77LJueZyoa/slP0s3wMWtCtJTvNHoAdtwHXBNUMBPig3m1kO
  AEMhdwPFXkNlVlGizebWmyfuWWF2E6PdfE4V8Jf1BONXZY2gJNHpqNdkQEZS5/mQ
  CBSiTlZe/Y5/rMcwDuXKeN7yzMYxvSzBMqUzYBl5kL7PtSkuQgOss7yvhhrhkASb
  MNUCAwEAAaNwMG4wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
  BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFM7ve6dIWkNtAew1
  hgqagIlBsZ+vMA4GA1UdEQQHMAWCA2FwaTANBgkqhkiG9w0BAQsFAAOCAQEAKOH0
  oc4sHyo2m8ynLMBT3Qe/XXx+3NOqsfqPDwm0wl/ibB1MbyGi7t2xsD75KLHWYZAn
  TwTjElVHyfd356LRwSxDn2aOdyaPAZsioOIYMlEpfcLIP3xCFFUjOKI9TKSCE9uE
  xD1CH6l1LD/PEV9Bra/4h9cXDppQEKqFBO9he6bALgD6LzEOIQHyTCNRMpFC+XCR
  0S8zuiQTBwQeinnY+iL+3k+RA8jPUxWkVLG+H052v7D1fXRSRMUnTgAWBWjE9J8x
  /a+DO7Qc30KBVpVXRAyOJS0fiD9HDgeqtInfhVzyM6Ips+K/zYQwO6+qrBoWyWPF
  UmW6PilF3Esy7Z5U0g==
  -----END CERTIFICATE-----
client_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEA8TEmXEh6H4iXARU+oYjjv/uHodf4GxMNAB1LJHp5N0Hy/5LA
  VD/PpnBkC4eHqpr3cGzc6YqMUjBAGXQvwOfVHKNGqu7Q5SQSfVn2zBpmpGNKybAn
  VenuTI2PxpbEW/84R/080Fps5PzJJZ+YVNXe9u7i8pXJ/rqe1CPvssm55nKhr+yU
  /SzfAxa0K0lO80egB23AdcE1QwE+KDebWQ4AQyF3A8VeQ2VWUaLN5tabJ+5ZYXYT
  o918ThXwl/UE41dljaAk0emo12RARlLn+ZAIFKJOVl79jn+sxzAO5cp43vLMxjG9
  LMEypTNgGXmQvs+1KS5CA6yzvK+GGuGQBJsw1QIDAQABAoIBAQCKRTYLo5U3bLO8
  8DP2oSaH0iggdVKMGvDSBvkkEX5aWll3gOb3pZlifn4sSedRvANslUxUKpRlLboh
  nYUe3wlCoKwLpFtncbWT3TZqLhx302B1naH/U9vEUUeCfr5VS0w1oQzzGVPiNrUN
  9595yx5GjA7ZKVwix1P0pCFvasxDOolgYBjS5oqurmdOCMAH8zjXxiSiCcmlHb9G
  wMcDRVG8VvHuZvUeP+qA0zXHaiMB9ZX3TPijXzSva76FDkVT7v6y301d7mmeYgQ/
  wzhySC7+ZFVZ6fW6zX0+FPDCxbhsyte9fgL2QnKRKaWUkc78v/+AlHIRcbyoSh3X
  vs/jWW3BAoGBAPXVZtPyVeRAb/OSFPQspCIPOyq3uav3JTyHafYOjPhDF96GF/nM
  TsG5Xb5RT0B9Aamhet40sUg+KsDkhsEUWQtRQPYzLAjajPL8bbDXLIwsw4kZEQ4h
  7WZs5z3jUBPOrl4rsVR5MyZCSDsITzKpRY3R5Iq8qLdNgRnBn9BPNtjRAoGBAPsq
  m7amv/cpQmD8FePKB7lWgA3/SfBJfEwq1hGvIKFKsPeYWN72L2XaqIKvTkd4/v0i
  d8dGFjOKQcasxK5m18u/TF4fwsk52N8gDICK3BsxrLfh/3MtPGaOtVOlKQl9Zs3K
  H+xHuWfSrutvS4a88no/Nxwkb+Gg9tlpJh1eltjFAoGBAKxLQKJTOfebYdsoCx+H
  GhH08tbhpXPs52Ag2Bbn480r2NLQ0IT2uEv2CsmUWyMrebrVvjN2YrnrODOw9vDj
  vfS8ofbrrnUWF6tFV+uVI1erF/BCbT2mcahTs04gvsLjHDpMDSDTQRITamRVUoyD
  LohTDwZdazHtVAolNkjc++fBAoGAYp3ELd8jGGR2z6Wq4pl8luTDurs1yMbRqwZW
  rvLYGPw+p7iFjGWVDqTf7Q/v6Fg1piZWaUO3i90JHnzPbLqsmC8wSPSngmLYKCNp
  RT9AVN0YN8rghdSJFquJvqHmjvdR2hM2nYs73Ov4CjDUsr6VZjJT7RTRaQHOambC
  tF1jVRECgYEAgM3F1j73wJWVSvqEa9io02XX7uYRTuCo8TpxYkdfZSwAfWvO8SQe
  Jx30G42NtG6NuIpW2asWvuhZJN5Or58T9ewgiLQ7vKawcwibeokyANIQY4di5eB+
  XfIkQdEES/Lx50rpWfkdxVSkj8KBYIEjCu9pU93zIW2P7fKCUEuSDDk=
  -----END RSA PRIVATE KEY-----
api_connection_string: 0.0.0.0:8001
name: api
